2019-06-30 12:34:35,521ERROR:Exception on /follow/mdevaney [GET][inc:\matt's~1\python\microb~1\venv\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "c:\matt's~1\python\microb~1\venv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\matt's~1\python\microb~1\venv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\matt's~1\python\microb~1\venv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\matt's~1\python\microb~1\venv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\matt's~1\python\microb~1\venv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\matt's~1\python\microb~1\venv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\matt's~1\python\microb~1\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Matt's Files\Python\microblog\app\routes.py", line 103, in follow
    user = User.query.filter_by(username=username).first()
UnboundLocalError: local variable 'user' referenced before assignment
2019-06-30 20:49:23,003INFO:Microblog startup[inC:\Matt's Files\Python\microblog\app\__init__.py:53]
2019-06-30 20:49:24,516ERROR:Exception on / [GET][inc:\matt's~1\python\microb~1\venv\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "c:\matt's~1\python\microb~1\venv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\matt's~1\python\microb~1\venv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\matt's~1\python\microb~1\venv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\matt's~1\python\microb~1\venv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\matt's~1\python\microb~1\venv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\matt's~1\python\microb~1\venv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\matt's~1\python\microb~1\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Matt's Files\Python\microblog\app\routes.py", line 25, in index
    return render_template('index.html', title='Home Page', form=form, posts=posts)
  File "c:\matt's~1\python\microb~1\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\matt's~1\python\microb~1\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\matt's~1\python\microb~1\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\matt's~1\python\microb~1\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\matt's~1\python\microb~1\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\matt's~1\python\microb~1\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Matt's Files\Python\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Matt's Files\Python\microblog\app\templates\base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Matt's Files\Python\microblog\app\templates\index.html", line 15, in block "content"
    <p>{{ form.submit() }}</p>
jinja2.exceptions.UndefinedError: 'app.forms.PostForm object' has no attribute 'submit'
2019-06-30 20:49:27,007ERROR:Exception on /index [GET][inc:\matt's~1\python\microb~1\venv\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "c:\matt's~1\python\microb~1\venv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\matt's~1\python\microb~1\venv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\matt's~1\python\microb~1\venv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\matt's~1\python\microb~1\venv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\matt's~1\python\microb~1\venv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\matt's~1\python\microb~1\venv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\matt's~1\python\microb~1\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Matt's Files\Python\microblog\app\routes.py", line 25, in index
    return render_template('index.html', title='Home Page', form=form, posts=posts)
  File "c:\matt's~1\python\microb~1\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\matt's~1\python\microb~1\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\matt's~1\python\microb~1\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\matt's~1\python\microb~1\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\matt's~1\python\microb~1\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\matt's~1\python\microb~1\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Matt's Files\Python\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Matt's Files\Python\microblog\app\templates\base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Matt's Files\Python\microblog\app\templates\index.html", line 15, in block "content"
    <p>{{ form.submit() }}</p>
jinja2.exceptions.UndefinedError: 'app.forms.PostForm object' has no attribute 'submit'
2019-06-30 20:49:28,957ERROR:Exception on /index [GET][inc:\matt's~1\python\microb~1\venv\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "c:\matt's~1\python\microb~1\venv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\matt's~1\python\microb~1\venv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\matt's~1\python\microb~1\venv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\matt's~1\python\microb~1\venv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\matt's~1\python\microb~1\venv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\matt's~1\python\microb~1\venv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\matt's~1\python\microb~1\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Matt's Files\Python\microblog\app\routes.py", line 25, in index
    return render_template('index.html', title='Home Page', form=form, posts=posts)
  File "c:\matt's~1\python\microb~1\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\matt's~1\python\microb~1\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\matt's~1\python\microb~1\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\matt's~1\python\microb~1\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\matt's~1\python\microb~1\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\matt's~1\python\microb~1\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Matt's Files\Python\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Matt's Files\Python\microblog\app\templates\base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Matt's Files\Python\microblog\app\templates\index.html", line 15, in block "content"
    <p>{{ form.submit() }}</p>
jinja2.exceptions.UndefinedError: 'app.forms.PostForm object' has no attribute 'submit'
